# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorUsername', models.CharField(max_length=50)),
                ('DoctorPassword', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedName', models.CharField(max_length=50)),
                ('MedXLoc', models.IntegerField(default=0)),
                ('MedYLoc', models.IntegerField(default=0)),
                ('MedQuantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientCred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientUsername', models.CharField(max_length=50)),
                ('PatientPassword', models.CharField(max_length=50)),
                ('AssignedDoctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.DoctorCred')),
            ],
        ),
    ]
